/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as GroupsNewRouteImport } from './routes/groups.new'
import { Route as SettleGroupIdRouteImport } from './routes/settle.$groupId'
import { Route as SplitAmountRouteImport } from './routes/split.amount'
import { Route as SplitScanRouteImport } from './routes/split.scan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsNewRoute = GroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettleGroupIdRoute = SettleGroupIdRouteImport.update({
  id: '/settle/$groupId',
  path: '/settle/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitAmountRoute = SplitAmountRouteImport.update({
  id: '/split/amount',
  path: '/split/amount',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitScanRoute = SplitScanRouteImport.update({
  id: '/split/scan',
  path: '/split/scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/new': typeof GroupsNewRoute
  '/settle/$groupId': typeof SettleGroupIdRoute
  '/split/amount': typeof SplitAmountRoute
  '/split/scan': typeof SplitScanRoute
  '/groups/': typeof GroupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/new': typeof GroupsNewRoute
  '/settle/$groupId': typeof SettleGroupIdRoute
  '/split/amount': typeof SplitAmountRoute
  '/split/scan': typeof SplitScanRoute
  '/groups': typeof GroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/new': typeof GroupsNewRoute
  '/settle/$groupId': typeof SettleGroupIdRoute
  '/split/amount': typeof SplitAmountRoute
  '/split/scan': typeof SplitScanRoute
  '/groups/': typeof GroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/onboarding'
    | '/profile'
    | '/groups/$groupId'
    | '/groups/new'
    | '/settle/$groupId'
    | '/split/amount'
    | '/split/scan'
    | '/groups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/onboarding'
    | '/profile'
    | '/groups/$groupId'
    | '/groups/new'
    | '/settle/$groupId'
    | '/split/amount'
    | '/split/scan'
    | '/groups'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/onboarding'
    | '/profile'
    | '/groups/$groupId'
    | '/groups/new'
    | '/settle/$groupId'
    | '/split/amount'
    | '/split/scan'
    | '/groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  GroupsNewRoute: typeof GroupsNewRoute
  SettleGroupIdRoute: typeof SettleGroupIdRoute
  SplitAmountRoute: typeof SplitAmountRoute
  SplitScanRoute: typeof SplitScanRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/new': {
      id: '/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof GroupsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settle/$groupId': {
      id: '/settle/$groupId'
      path: '/settle/$groupId'
      fullPath: '/settle/$groupId'
      preLoaderRoute: typeof SettleGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split/amount': {
      id: '/split/amount'
      path: '/split/amount'
      fullPath: '/split/amount'
      preLoaderRoute: typeof SplitAmountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split/scan': {
      id: '/split/scan'
      path: '/split/scan'
      fullPath: '/split/scan'
      preLoaderRoute: typeof SplitScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  GroupsNewRoute: GroupsNewRoute,
  SettleGroupIdRoute: SettleGroupIdRoute,
  SplitAmountRoute: SplitAmountRoute,
  SplitScanRoute: SplitScanRoute,
  GroupsIndexRoute: GroupsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
