/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HomeRouteImport } from './routes/home'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ExpenseExpenseIdRouteImport } from './routes/expense.$expenseId'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as GroupsNewRouteImport } from './routes/groups.new'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as SettleGroupIdRouteImport } from './routes/settle.$groupId'
import { Route as SplitAmountRouteImport } from './routes/split.amount'
import { Route as SplitItemsRouteImport } from './routes/split.items'
import { Route as SplitResultRouteImport } from './routes/split.result'
import { Route as SplitReviewRouteImport } from './routes/split.review'
import { Route as SplitScanRouteImport } from './routes/split.scan'
import { Route as SplitShareRouteImport } from './routes/split.share'
import { Route as SplitStartRouteImport } from './routes/split.start'
import { Route as GroupsGroupIdEditRouteImport } from './routes/groups.$groupId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseExpenseIdRoute = ExpenseExpenseIdRouteImport.update({
  id: '/expense/$expenseId',
  path: '/expense/$expenseId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsNewRoute = GroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SettleGroupIdRoute = SettleGroupIdRouteImport.update({
  id: '/settle/$groupId',
  path: '/settle/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitAmountRoute = SplitAmountRouteImport.update({
  id: '/split/amount',
  path: '/split/amount',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitItemsRoute = SplitItemsRouteImport.update({
  id: '/split/items',
  path: '/split/items',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitResultRoute = SplitResultRouteImport.update({
  id: '/split/result',
  path: '/split/result',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitReviewRoute = SplitReviewRouteImport.update({
  id: '/split/review',
  path: '/split/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitScanRoute = SplitScanRouteImport.update({
  id: '/split/scan',
  path: '/split/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitShareRoute = SplitShareRouteImport.update({
  id: '/split/share',
  path: '/split/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitStartRoute = SplitStartRouteImport.update({
  id: '/split/start',
  path: '/split/start',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdEditRoute = GroupsGroupIdEditRouteImport.update({
  id: '/groups/$groupId_/edit',
  path: '/groups/$groupId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/receipts': typeof ReceiptsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/expense/$expenseId': typeof ExpenseExpenseIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/new': typeof GroupsNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/settle/$groupId': typeof SettleGroupIdRoute
  '/split/amount': typeof SplitAmountRoute
  '/split/items': typeof SplitItemsRoute
  '/split/result': typeof SplitResultRoute
  '/split/review': typeof SplitReviewRoute
  '/split/scan': typeof SplitScanRoute
  '/split/share': typeof SplitShareRoute
  '/split/start': typeof SplitStartRoute
  '/groups/': typeof GroupsIndexRoute
  '/groups/$groupId/edit': typeof GroupsGroupIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/receipts': typeof ReceiptsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/expense/$expenseId': typeof ExpenseExpenseIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/new': typeof GroupsNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/settle/$groupId': typeof SettleGroupIdRoute
  '/split/amount': typeof SplitAmountRoute
  '/split/items': typeof SplitItemsRoute
  '/split/result': typeof SplitResultRoute
  '/split/review': typeof SplitReviewRoute
  '/split/scan': typeof SplitScanRoute
  '/split/share': typeof SplitShareRoute
  '/split/start': typeof SplitStartRoute
  '/groups': typeof GroupsIndexRoute
  '/groups/$groupId/edit': typeof GroupsGroupIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/receipts': typeof ReceiptsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/expense/$expenseId': typeof ExpenseExpenseIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/new': typeof GroupsNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/settle/$groupId': typeof SettleGroupIdRoute
  '/split/amount': typeof SplitAmountRoute
  '/split/items': typeof SplitItemsRoute
  '/split/result': typeof SplitResultRoute
  '/split/review': typeof SplitReviewRoute
  '/split/scan': typeof SplitScanRoute
  '/split/share': typeof SplitShareRoute
  '/split/start': typeof SplitStartRoute
  '/groups/': typeof GroupsIndexRoute
  '/groups/$groupId_/edit': typeof GroupsGroupIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/auth'
    | '/home'
    | '/onboarding'
    | '/profile'
    | '/receipts'
    | '/reset-password'
    | '/expense/$expenseId'
    | '/groups/$groupId'
    | '/groups/new'
    | '/invite/$token'
    | '/join/$token'
    | '/settle/$groupId'
    | '/split/amount'
    | '/split/items'
    | '/split/result'
    | '/split/review'
    | '/split/scan'
    | '/split/share'
    | '/split/start'
    | '/groups/'
    | '/groups/$groupId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/auth'
    | '/home'
    | '/onboarding'
    | '/profile'
    | '/receipts'
    | '/reset-password'
    | '/expense/$expenseId'
    | '/groups/$groupId'
    | '/groups/new'
    | '/invite/$token'
    | '/join/$token'
    | '/settle/$groupId'
    | '/split/amount'
    | '/split/items'
    | '/split/result'
    | '/split/review'
    | '/split/scan'
    | '/split/share'
    | '/split/start'
    | '/groups'
    | '/groups/$groupId/edit'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/auth'
    | '/home'
    | '/onboarding'
    | '/profile'
    | '/receipts'
    | '/reset-password'
    | '/expense/$expenseId'
    | '/groups/$groupId'
    | '/groups/new'
    | '/invite/$token'
    | '/join/$token'
    | '/settle/$groupId'
    | '/split/amount'
    | '/split/items'
    | '/split/result'
    | '/split/review'
    | '/split/scan'
    | '/split/share'
    | '/split/start'
    | '/groups/'
    | '/groups/$groupId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AuthRoute: typeof AuthRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ReceiptsRoute: typeof ReceiptsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ExpenseExpenseIdRoute: typeof ExpenseExpenseIdRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  GroupsNewRoute: typeof GroupsNewRoute
  InviteTokenRoute: typeof InviteTokenRoute
  JoinTokenRoute: typeof JoinTokenRoute
  SettleGroupIdRoute: typeof SettleGroupIdRoute
  SplitAmountRoute: typeof SplitAmountRoute
  SplitItemsRoute: typeof SplitItemsRoute
  SplitResultRoute: typeof SplitResultRoute
  SplitReviewRoute: typeof SplitReviewRoute
  SplitScanRoute: typeof SplitScanRoute
  SplitShareRoute: typeof SplitShareRoute
  SplitStartRoute: typeof SplitStartRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  GroupsGroupIdEditRoute: typeof GroupsGroupIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense/$expenseId': {
      id: '/expense/$expenseId'
      path: '/expense/$expenseId'
      fullPath: '/expense/$expenseId'
      preLoaderRoute: typeof ExpenseExpenseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/new': {
      id: '/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof GroupsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settle/$groupId': {
      id: '/settle/$groupId'
      path: '/settle/$groupId'
      fullPath: '/settle/$groupId'
      preLoaderRoute: typeof SettleGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split/amount': {
      id: '/split/amount'
      path: '/split/amount'
      fullPath: '/split/amount'
      preLoaderRoute: typeof SplitAmountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split/items': {
      id: '/split/items'
      path: '/split/items'
      fullPath: '/split/items'
      preLoaderRoute: typeof SplitItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split/result': {
      id: '/split/result'
      path: '/split/result'
      fullPath: '/split/result'
      preLoaderRoute: typeof SplitResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split/review': {
      id: '/split/review'
      path: '/split/review'
      fullPath: '/split/review'
      preLoaderRoute: typeof SplitReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split/scan': {
      id: '/split/scan'
      path: '/split/scan'
      fullPath: '/split/scan'
      preLoaderRoute: typeof SplitScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split/share': {
      id: '/split/share'
      path: '/split/share'
      fullPath: '/split/share'
      preLoaderRoute: typeof SplitShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split/start': {
      id: '/split/start'
      path: '/split/start'
      fullPath: '/split/start'
      preLoaderRoute: typeof SplitStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId_/edit': {
      id: '/groups/$groupId_/edit'
      path: '/groups/$groupId/edit'
      fullPath: '/groups/$groupId/edit'
      preLoaderRoute: typeof GroupsGroupIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AuthRoute: AuthRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ReceiptsRoute: ReceiptsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ExpenseExpenseIdRoute: ExpenseExpenseIdRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  GroupsNewRoute: GroupsNewRoute,
  InviteTokenRoute: InviteTokenRoute,
  JoinTokenRoute: JoinTokenRoute,
  SettleGroupIdRoute: SettleGroupIdRoute,
  SplitAmountRoute: SplitAmountRoute,
  SplitItemsRoute: SplitItemsRoute,
  SplitResultRoute: SplitResultRoute,
  SplitReviewRoute: SplitReviewRoute,
  SplitScanRoute: SplitScanRoute,
  SplitShareRoute: SplitShareRoute,
  SplitStartRoute: SplitStartRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  GroupsGroupIdEditRoute: GroupsGroupIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
